base_url = "https://ariedro.dev"
title = "ariedro's page"
theme = "terminimal"
compile_sass = true
build_search_index = false
taxonomies = [
    {name = "tags"}
]
generate_feeds = true

[markdown]
highlight_code = true

[extra]
logo_text = "ariedro's page"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "about", url = "$BASE_URL/about"},
    {name = "hire", url = "https://hire.ariedro.dev/"},
    {name = "contact", url = "$BASE_URL/contact"},
    {name = "rss", url = "$BASE_URL/atom.xml"},
]
copyright_html = "ariedro 2022-$CURRENT_YEAR - made with Zola, using Terminimal theme"